name: SennetIdle
main: me.senseiju.sennetidle.SennetIdle
version: ${version}
api-version: 1.17
depend:
  - ProtocolLib
  - HolographicDisplays
  - PlaceholderAPI

author: SenseiJu
website: https://senseiju.me